### ISSUE TITLE
Should the properly typed stringify live here?

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript-globals#15] opened 2017-07-13 16:49 UTC
Brought this up the other day, but it would be good (for me, at least, when using and teaching Purescript) to have the properly typed `stringify` in here: https://twitter.com/paf31/status/884984889942167553

I think some concerns revolve around whether or not we should export the class at all (I don't know how this would work with newtypes), etc.

**Comment by paf31** [comment] 2017-07-13 16:50
The problem is that constructing the dictionaries makes this possibly quite inefficient.

**Comment by safareli** [comment] 2018-03-02 08:48
@paf31 when class definition is empty can we optimize it to not result in constructing dictionaries?

(if there is issue for it can you link please)

**Comment by garyb** [comment] 2018-03-02 10:13
purescript/purescript#2768

**Comment by garyb** [comment] 2018-05-13 16:58
I guess we can close this now it's in prelude :smile:

**Closed by garyb** 2018-05-13 16:58 UTC

**Comment by garyb** [comment] 2018-05-13 18:27
It’s the show instance for records.

**Comment by safareli** [comment] 2018-05-13 18:36
Ah it's in [compiler/0.12](https://github.com/purescript/purescript-prelude/blob/compiler/0.12/src/Data/Show.purs) branch
